// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"ChaoXing_SignIn_GoRebuild/internal/dao/internal"
)

// internalChaoxingUserDao is internal type for wrapping internal DAO implements.
type internalChaoxingUserDao = *internal.ChaoxingUserDao

// chaoxingUserDao is the data access object for table chaoxing_user.
// You can define custom methods on it to extend its functionality as you wish.
type chaoxingUserDao struct {
	internalChaoxingUserDao
}

var (
	// ChaoxingUser is globally public accessible object for table chaoxing_user operations.
	ChaoxingUser = chaoxingUserDao{
		internal.NewChaoxingUserDao(),
	}
)

// Fill with you ideas below.
