// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package chaoxing

import (
	"ChaoXing_SignIn_GoRebuild/api/chaoxing"
)

type ControllerV1 struct{}

func NewV1() chaoxing.IChaoxingV1 {
	return &ControllerV1{}
}
